apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nanobot
  namespace: argo-cd
spec:
  project: spof-cluster
  source:
    repoURL: "https://github.com/SP0Fs/cluster.git"
    targetRevision: HEAD
    path: apps/nanobot/resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nanobot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
