apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openthread-data
  namespace: openthread
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd