apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: github-actions-runner
spec:
  encryptedData:
    github_token: AgBQ3hH59ozarrhAjM5YonHNNuVDpsRiETkLh7107HRGrfr/F6JNEDwSpv2uQl6JdU5eHJY4j47ItMpdkyvHzf0LSkkqYHODxbM8mVmuEypwpxP2OfMtIcGZYlBwg32G3vzBcRE9pQfFxBg8EYZjzutKs1Il8QtmFqm8J8FXKwJAKO9fxT+jXtFL2Uiq484SISEvxVNTQuq8meiSVC6YGDqrvT0eDlzEsZ8LaiO9gvKIC8cA95Arn/Lzod4IYxYvTO1Ip5rqX6DfbvZGbk7k2OBzKNjF/FnXV94aj82XXPovnm8XUsdIcZTBAoNBdf5UTmIBUcc/llcOQIJTGJdFxpBDCvEzdkBnQJJOmSV4LmWu3+tGv1H8Va+Hy9R4H4hNGoM+l81KD0QeBFxNynDnFfDyYgGdIFb9wAS8IScSZIXXdNaRpHDIdHPH3NmC7dhDlacyBfzUvjWpLdDn6pFDOFJdRKMe3rWIBnFL5jpaRyIhTue1OGEUZyNywXgAaC4HvrP3HjxctxlNxxidZydon9hZlXdJ0H2WSbQy+yi4VrN+rsE8ayoQlOMEHcGwKZ+zAskvss90FRuYZEcp9dqqKllVwEey7cODfAdaJA13vLQhXEj1E0Dmc6Z12/sf1FMXqi3+9V4gYN4xwa+6qIaqtIXhDlyg4zPp2ir++ET0WwVT7JxevWImVSPFxMUny4GwkY6HCA9aiibQB6ZJFF+WXdwLZtqzCvogG4t3dtqCCOFx7wbKlzqYv0PX
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: github-actions-runner
    type: Opaque
