apiVersion: v1
kind: Secret
metadata:
  name: matrix-secret
  namespace: matrix
type: Opaque
data:
  secrets.yaml: ZGF0YWJhc2U6CiAgbmFtZTogc3luYXBzZQogIHBhc3N3b3JkOiBjaHVfUDlrZTlvb3NvaHBoMW9vbAptYWNhcm9vbl9zZWNyZXRfa2V5OiBFeGVpM293aWV0aHU1VnVuZ2FpemU3cGhlZWMwdWl5ZWVjaGFpNmRvby5jaHV1WTBUYWVRdTFvb0RlaUwKcmVnaXN0cmF0aW9uX3NoYXJlZF9zZWNyZXQ6IDViOGY1ZDIyOWQ0OGNlMWMyODVmODVmY2I4ZjUyYzhjZWJkZWE0NzlhNDVkOWFmYzBkNGFlMTg3MjMyOTJjYmMKc2lnbmluZ19rZXk6IGVkMjU1MTkgYV9kdFh0IFlYck1WYW50TCsxdGNseW5DNWcvNTVvY2F2b296cVl0WlUrTm5pMGMzOUk=