---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-root-user
  namespace: mongodb
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgDPIUpEP4n9taT0ekCvWveqB0VjNEfprK+wDVlCgOSByrfpzgghwXmJb7ObDu1VjFllaYtfq2jE81U+7rlR0qJzC7HNu2jhmvXUaI74rvhUhJwb9zjeyenysk1ESuKiGOIjZpANw5XmIJxv71THxHhhXG4Q6+sUDpMNqi+mO7JuEsnmHr7gBjHaI8IaJxpltX4E+swu2hicl0J3fXdIkKlh7rKy29hksKds24J+3cxXsNqakxZjqOOpkGGZK82QHP0wi+epHxxHfcAr51s2uC2JH9+uAhZ/nZwLOj6lxm2/azmOs6mfcknLRRGCMDD0vKzCseEa2XPosRi/4Ie0sOuO0SnLYBJxAJUq515DcauWFZtNwI77K/qEkcIx3CymrUbNn5pOB5LLKGSLy64nQtQIkzdBjjZYm1CHt3M/JhMRwd1p/QqksqhotMWT5SyvLw5XUSPTsnz5cqlxrFajHm9p3yoAc0gZz7OueYYpLViQfHonmAAffNajIroosH2mO7oE5LutFFpt/CevAnwxs0x6R+HQ8yhj6vUwLQvEVXML42ZfuwFde6tHABQiFLZFRVX9LRpCP9q4VHPXC4FLZ7nRQJk5JR7JDwaZCFjtbgtfXy0/LbDKvRnFwqVMP7+W7KYP5uGQpt0yAyTfFXA28MQ3VlTlBthmqg///uM2SZhxIX+/Ksnu5dwQEHp869Tr91x3RPBKepPUWxk2go6SCWZyC/GcjLAL8r1rRw5uRrZ9MA==
    MONGO_INITDB_ROOT_USERNAME: AgATVG8raY9e02LtLCwc+vYi9fCYYE+WDSguochTqP021oV2Jm7XI/puyr4Y/IjDffScBceAlnt23tel4mrIJKzphdJwXEKEVnT8eDFUKSTe2TtH52kvHsN1VLuPAb0jDu3YZlCVflujQP/bGGMK8dxjes9Ve2QSFRWTLVlRDK2dFsy68irD5x7qPBrRg2v1EaohFaMF9qvTiNqXyq3PjP24qadcXtrPNq1MgOJty2rC+krtO9tuhITs3SlECG9KYsq462Y+3H1WlfhMg0T2VCtc9Ws4ENFSz9Vp7SySIYwt06MUWe5sFGhZJGUT4DUGblnEr+qR1Hc4LdRmpaLpueS4s52Y52V7kybX3i12mtkQ9jeTPBEjOvXozKtWCWDo7kBM18StNni/eKy4paryBxaWWctYOkeNp6xwdzwyqEcmxFT3k6uJ8zg7JWGTsJeCpK+TUzM1Swogh7rW/xxfqRAdi+h0daPQvvylZQpE+2qi3CDbmHKP8o5ZUc0lb1Nvpa9VQYBOzkBd49Ii24q1bEegX7ca2+4Ak2MeyY/pkqvQwvQgw/0RNTPebqKJyhKyYAX41Q1VbsJ9vBEVzewTQPHuZSg6irT2ttUA7D1QLBU9K/WuPa/1JYctaPqnGs7DpCxbWLkwCxVGMdAqJUyDSMM6fIbiOVI6jW5h9jQxmX8w5IvI0ORV1h68vIvJWLPqN4GWu70HuQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-root-user
      namespace: mongodb
