apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-hub-public-key
  namespace: monitoring
spec:
  encryptedData:
    ssh-key: AgAcszbsMkwMYLw2h6BX9zwnP48kGdfeaY1XEP3RxQT+LrXuBHtBufzQaMhonJ02WMEiu2/X5bv8mwyv1yyfidgg8V84dnGEY7f54uEz3mvKbyNpP0PDdpdjYpXmSL4vjERAl6yTwsKHJTeo1iSKQQRDT0Vk2dhn073zidK1Cbo3FCEH6KxUBMvzdlF0+ENksu5UttRAXQV2hZgWLMLeDlAosDT0yCYjFeXUb06IEGE4BaSva3g54CrJriROkUKvM9gHL4yeTr1yTO5Ojww6whsmoR+hqgthFlgN7sWqCQlBOxwJU1f295g3jLUCgZfeGbA01AmEHe/Yy5534ryDl7nxOj9VQQdTMRow+YtUAIvl0tZgoMr6fdXdWhdXiQnNI5nhs3jYYurLYn4TSG+duA3C2w3CC6vrEahMwJlE9NdjfuKKZ+uJCzQLVLCDMsFA4TB3dVSUlafGinWO37q1Qu9KkN9EShm07bOd4k7XzPmG3aXtmKQsJbW4/lKi4KSMX2dBzLtTqbspyldnJ6OAirgaZLBNQ0eYNHDYtFn9O1HnyDG3GgLmSNllFgEOy4Bb1GYm55bdjBM4agQkRIPR7Aft/dj4Nu6YkjKmCLqEaKpYC+GvZ0bOAZMNeZFYJ2IC9N6Irx25Jm6oSPN9xb4J6OgMaC4lzsa52j/3XBPitCFOB3ZaqZ2/Q7qIT/l8CEjc/B12yagS1o+eMdDanZCp65eZufVIjG6s4cM83TmO73CG7VMYuDQgwBZk+hld8A+q69WBdSoB5M1k/PETG/n1qNJ9EqN2JdDHdXqPXRZte6twmewzkSUcRRq3
  template:
    metadata:
      name: beszel-hub-public-key
      namespace: monitoring
    type: Opaque
