apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nanobot
  labels:
    app: nanobot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nanobot
subjects:
  - kind: ServiceAccount
    name: nanobot
    namespace: nanobot