apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nanobot
  labels:
    app: nanobot
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bitnami.com"]
    resources: ["sealedsecrets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - nonResourceURLs: ["/version", "/healthz", "/metrics"]
    verbs: ["get"]