apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-homeassistant
  namespace: postgres
spec:
  encryptedData:
    password: AgB+6wWpTpvnDkexYa4jjaK01ETroc8oks9uAjo3eu8zDmj5SswxKbzHXHI6gUtbTZ0U9HPgmCOeJyJtTJJgC7TEUHrBx+oPmv4OFtEv6TPSbDeqlabffv1Qxgq90SpdYMgG30ZPFLejVO6u4TvYkdLVQ8Q+WZ3mPmHZZAL1Y1NNmovJL3eHRpduNzeKjt3Jee1SMcXtlK+8+UvKXBgnTLR1sFKp4kCoPTtDZM2KkgdHT2RJdavQaAh5fFgocuDBiL0eCFESeuRNCFknsyHwGWAyPmp7sZtN7ozVs3sqCyvMVVBd49lrKpQyx9SQCRYpFLZY80j9eEb5jPZi6ZpVwL7wnmK1r9evhwTAfAvBPhfffC4fvCjQp6Wf08qDEltXhlqWXRIx66k8a+NCOYElGfpkNqbNba0bwM25YLEg2Dkg0xEIUarccmK1I+1gV6RleRfGF1MQSysYuQ1xEPIl9lOFMc2XNJT2Or27rT2Sx3wm2DINrg8wugA/zHfStCOez0o9qrxYfOECBTvM/Oa5g1jFSGUh570sazFin8stG3AgL1m+RN7spRNHxXLD7giqSkMfeDLXYfIpxFLv2p7SYGy68MnAmqhQyAA4a6hTf5B2zeK/NZCNg6J5+RBRdid69WsAPB/n8IYU9PW6yA7OAXlLE1woB+0CdNR0bl62tRJfvrr3QiSECDuaCgT8e624Za3L7M8R6BAKzd9pCO+EnM+aT+J6dYITLBG76A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-homeassistant
      namespace: postgres
    type: Opaque

