apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: postgres
spec:
  encryptedData:
    password: AgBnIw0LDK8J66hOQaUVmLVeTtAdKweBcDoVloV5eZ2Yqd3z9DYjloPsWV8RmWNctGtx+m4wFtX7bAQCyIqIUKNJoJIexxi3iUyLZc8sv65QGLbyFdV41FEKKgIBYKJsyHMHutPuVa0y1EvLlAR+Km6YNUea7+4iisje46PeMo8dQDXciuoB30RTY1oRXItAX67i3H87DSvxQLuqzLmpIaD4/ibz6/Rs7yyEz0rLFhccv/nsSAY0Bj7Qew2RPOMQunTOfdhRm5HgMzlQxH2UyilGGMn5Ti5nvSeyPe0/PMPHj0aCWG8qUsmGeI3MfzfyKtFE05/3UAPUtjS8T3aZSVUUHqunOBCtHMRXE4HL3Duxrs2dz/WKEeKSX/DvWKQb5z/0D94uqJI6tKi5TMJVik4l+TMetimSsLKcjpF47iMfYHxCIyPeC05zIXVDBRuluWoXGaobfiCtINYvPujH/wcMNCl6fMRLmVh5oXOiVlvAJxjXw/a9c1hMggVSBHg+aujBFV7+yy1/bSeYNEpPyaeTMnE7YOV0mpxr/e6D45yOe0cj11R5yj2EYLroi+Bx7Dq4dS3aW5MLQfEy56ZZAR6AY5VAmTsv9vzfW9vzd8y71KKzr/S6Mm2fklkXo5yyjQHNdra9eGSTKfPpNrSJFp4YheLx7NoCry4Vnvn84/5BjIfVLWRFAnS7Z5Ta+sG5ZoJdvQfTfVW7f/AjBy777HDT33QAUA==
  template:
    metadata:
      name: postgres-synapse
      namespace: postgres
    type: Opaque
